set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

set -g pane-border-style fg="#170000"
set -g pane-active-border-style fg="#170000"

set-option -g allow-rename off
set-window-option -g automatic-rename off
set-option -g set-titles off

set -g status-left "[#S] "
set -g status-left-length 50

setw -g window-status-format "#I:#W"
setw -g window-status-current-format "#I:#W*"

set -g detach-on-destroy off
