unbind-key n
unbind-key p

bind ^ last-window

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind M-l next-window
bind M-h previous-window

bind L switch-client -n
bind H switch-client -p

bind-key -r B run-shell "~/.local/bin/tmux-sessionizer ~/work/boosting"
