unbind-key c

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

bind c new-window -n "terminal" -c "#{pane_current_path}"
bind n command-prompt -p "New window:" "new-window -n '%%' -c '#{pane_current_path}'"

bind O run-shell -b 'dir=#{q:pane_current_path}; \
  tmux new-window -n "agent.code" -c "$dir"; \
  tmux split-window -h -p 75 -c "$dir"; \
  tmux select-pane -L; \
  tmux split-window -v -p 33 -c "$dir"; \
  tmux select-pane -U; \
  tmux split-window -v -p 50 -c "$dir"; \
  tmux select-pane -R; \
  tmux send-keys "opencode -c" C-m'
