source-file ~/.config/tmux/conf.d/00-terminal.conf
source-file ~/.config/tmux/conf.d/10-prefix.conf
source-file ~/.config/tmux/conf.d/20-status.conf
source-file ~/.config/tmux/conf.d/30-windows.conf
source-file ~/.config/tmux/conf.d/40-copy-mode.conf
source-file ~/.config/tmux/conf.d/50-navigation.conf
source-file ~/.config/tmux/conf.d/60-clock.conf
source-file ~/.config/tmux/conf.d/70-bindings.conf

source-file -q ~/.config/tmux/conf.d/99-local.conf
